# https://github.com/marketplace/actions/delete-workflow-runs

name: Clean up

on:
    workflow_run:
        workflows: [Deploy to GitHub Pages]
        types:
            - completed

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

permissions:
    actions: write

jobs:
    clean_up:
        runs-on: ubuntu-latest
        steps:
            - name: Delete workflow runs (Deploy to GitHub Pages)
              uses: Mattraks/delete-workflow-runs@v2
              with:
                  token: ${{ github.token }}
                  repository: ${{ github.repository }}
                  retain_days: 0
                  keep_minimum_runs: 0
                  delete_workflow_pattern: Deploy to GitHub Pages
                  delete_run_by_conclusion_pattern: success
            - name: Delete workflow runs (self)
              uses: Mattraks/delete-workflow-runs@v2
              with:
                  token: ${{ github.token }}
                  repository: ${{ github.repository }}
                  retain_days: 0
                  keep_minimum_runs: 0
                  delete_workflow_pattern: Clean up
