name: Deploy to GitHub Pages

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

permissions:
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Download and extract remote tarball
              env:
                  REMOTE_TARBALL_URL: ${{ secrets.REMOTE_TARBALL_URL }}
              run: curl -fsSL "${REMOTE_TARBALL_URL:?invalid}" | tar -xzf -
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v1
              with:
                  path: '.'
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v1
